sudo: required

language: go

go:
  - 1.6

branches:
  only:
    - master

install:
- go get github.com/mitchellh/gox
- go get github.com/tools/godep
- ./script/godep-restore.sh

script:
- make binary
